### ISSUE TITLE
Add cron job to update matching results

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#1005]
- Configure a script which hits all graphQL endpoints for grants-round
- Filter rounds which are currently running (AKA active rounds) 
- And run the following queries to update the API service
```
# Round Summary
POST https://staging.grants.gitcoin.co/api/v1/update/summary/round/<chain-id>/<round-id>

# Match Summary
POST https://staging.grants.gitcoin.co/api/v1/update/match/round/<chain-id>/<round-id>
```
- Wire this into a cronjob via AWS and configure it to run every 30 minutes

**Comment by thelostone-mc** [comment]
note: we likely want to run the calculations after the round has ended so maybe when we filter active rounds, we include rounds which have just ended (AKA an hour after it's been ended)

**Comment by bhargavaparoksham** [comment]
@thelostone-mc For the matching amount in the grants explorer to work, we need cron job even when round's are active right?

**Comment by vacekj** [comment]
@bhargavaparoksham your suggestion here sounds correct to me, will implement that.

**Comment by vacekj** [comment]
After researching this, it seems the simplest and most elegant way to do this would be to:
- create a new endpoint in the api package that does the updates Nate mentioned above
- use this free service to trigger it as necessary: https://cron-job.org/en/
This way, we avoid the setup, deploy and management overhead of any new AWS resources. This endpoint is resource heavy, but if spamming becomes a problem, we can create a shared token, that the cron job will call the endpoint with, and the endpoint will verify that, or otherwise return and skip doing any work.

With AWS, the simplest would be a docker container that would do the above task, and be called using ECS Scheduled Tasks. However this feels like overkill for what we are trying to do here, as it involves creating the docker container, sharing code for graphql fetching etc. from other packages (which we don't yet have merged), managing the deployment via pulumi etc.

I'm keen on the first variant, just wanted to know your thoughts before I start this. @hmrtn @bhargavaparoksham @thelostone-mc

**Comment by thelostone-mc** [comment]
I'm good with us using cron-job as it's easier and cleaner
