### ISSUE TITLE
Review Grant Hub contract

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#146]
**Overview**

The goal of this task is to review the grant-hub contract and provide feedback.
The code can be found over at: 
https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts

**Comment by QEDK** [comment]
Initial observations:
* I am confident that `uint96` is actually less optimal given how EVM treats non-full words. It does save on amount of contract storage but that's pretty much it. https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L43
* if the intent is to just have an initializer, we should write a custom non-OZ initializer implementation to cut the weight on unrelated features (reinitialization) https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L69
* `metadata` should be stored in `calldata` if we are not mutating it
  * https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L78
  * https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L96
* we can label variables similar to the struct like `Project storage project` for readability https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L81
* error messages should be more descriptive or use a error code mechanism similar to Gnosis (https://github.com/gnosis/safe-contracts/blob/main/docs/error_codes.md)
  * https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L131
  * https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L132
* `projectOwnersCount()` should be `external` if we do not have internal calls to it https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L147
  * same with `getProjectOwners()` https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L155
* might be ideal to index parameters in events instead of saving gas https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L55
* the circular linked list approach is only efficient if we expect a decent number of owners, i would assume by usage of a multi-sig the number of owners would be limited, but I am not aware of the specifics

**Comment by gravityblast** [comment]
thank you @QEDK @thelostone-mc , I'm going to reply here in the next messages:

### uint96 for projects IDs

This can be definitely changed back to `uint256`. It was initially set as `uint96` to pack it together with the recipient address:

```
    struct Project {
        uint96 id;
        address recipient;
    }
```

but now that we removed the recipient, we can go back to have it as a `uint256`.

**Comment by gravityblast** [comment]
> the circular linked list approach is only efficient if we expect a decent number of owners, i would assume by usage of a multi-sig the number of owners would be limited, but I am not aware of the specifics

@QEDK we used a linked list to be able to both iterate/return all owners, and to check that an address is in the list without having to iterate through all (used in the `onlyProjectOwner` modifier).

A simple array would be good to store the owners and return them, but the `onlyProjectOwner` modifier would need to iterate through them to check if `msg.sender` is included.

A simple `mapping` would be good for the `onlyProjectOwner` modifier, but it would allow to return the full list.

wdyt?

**Comment by gravityblast** [comment]
> Do you have a script / example I could check out how this upgrade works ?

@thelostone-mc we have this script you can try if you create a new version of the `ProjectRegistry` contract

https://github.com/gitcoinco/grant-hub/blob/main/contracts/scripts/migrations/002-upgrade-project-registry.ts

**Comment by QEDK** [comment]
> > if the intent is to just have an initializer, we should write a custom non-OZ initializer implementation to cut the weight on unrelated features (reinitialization) https://github.com/gitcoinco/grant-hub/blob/main/contracts/contracts/ProjectRegistry.sol#L69
> 
> @QEDK we are using it just for the next implementation upgrades in case we need to initialize new variables. why would you use a non OZ initialize?

It depends on the pattern you want to use, the most common proxy pattern is the EIP-897 `DelegateProxy` approach which does not work with reinitialization. An in general, proxy patterns do not fit in well with reinitialization.

**Comment by gravityblast** [comment]
> not exactly, since search in linked list is also in O(n) time (like array search), you can perform the same search in O(n)

@QEDK in our case the search we need in `onlyProjectOwner` is actually constant because we can check if the owner exists directly with the map, not using the linked list, doing: `projectsOwners[projectID].list[msg.sender]`. so we don't need to loop through all the list.

For deletion we use the same pattern used in Gnosis Safe, the client sends the owner to remove and the previous owner in the list, so the search and removal are again constant. 

wdyt, does it make sense?

**Comment by QEDK** [comment]
> > not exactly, since search in linked list is also in O(n) time (like array search), you can perform the same search in O(n)
> 
> @QEDK in our case the search we need in `onlyProjectOwner` is actually constant because we can check if the owner exists directly with the map, not using the linked list, doing: `projectsOwners[projectID].list[msg.sender]`. so we don't need to loop through all the list.
> 
> For deletion we use the same pattern used in Gnosis Safe, the client sends the owner to remove and the previous owner in the list, so the search and removal are again constant.
> 
> wdyt, does it make sense?

does make sense to me, yes, in essence, it's a hash table + linked list, so it supports `O(1)` search/access at the cost of added space complexity `O(2n) ~= O(n)` It's pretty useful here, I concur.

**Comment by thelostone-mc** [comment]
Looks like that concludes are review changes. Closing this issue out now :D

**Comment by gravityblast** [comment]
thank you very much @thelostone-mc @QEDK , we addressed everything in the PR, if there's something else feel free to ping us!!
