### ISSUE TITLE
Update loading spinner

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#293]
**User Story:**
As a round operator
I want to see a cleaner loading spinner on Round Manager
So that I have more trust in the dApp

**Acceptance Criteria**
GIVEN that I am on Round Manager
WHEN a query is loading (for a list of programs, for a list of applications, etc)
THEN I see the updated loading spinner design

- Using tailwind spinner UI and centering (logo/message) on the list/table view.

**Product & Design Links:**
[Link to design](https://www.figma.com/file/K31Tf7tSn10BuN65VC6YLc/Round-Manager---Hi-Fidelity-Designs?node-id=1087%3A5441)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by nfrgosselin** [comment]
Hey @shavinac — this is working for me on the rounds in the "papa roti" test program, but it's redirecting to a blank screen when I do this within the "My Test" program. Check out this screen capture: https://share.vidyard.com/watch/K1K3Q6vyM7FkYqLxzPv81H?

**Comment by shavinac** [comment]
Copying over from discord convo:

* the round page is breaking because one of the received applications is using a new schema format with a signature
* grant hub had notified round manager team already about the change, but round manager has not yet implemented the changes to handle the new format (see https://github.com/gitcoinco/grants-round/issues/388)
* since the problem is not due to this story's loading spinner changes, nate will accept this story as-is and open new bug ticket

**Comment by nfrgosselin** [comment]
Accepting per above
