### ISSUE TITLE
spike: see where finalized votes should be uploaded and see what guard conditions have to be added

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#364]
**Overview**

Once a round has ended , we would need a function in the contract to store the final distribution.
The goal here is to find out 

- what all information we would store in the finalized distribution (distribution / other metadate like trust bonus score)
- how would we store this on-chain (merkle hash + IPFS hash ?)
- in which contract would we store this (against the round / voting contract )

**Acceptance Criteria**
- Document findings + present to team
- Pair with Nate on follow-on stories

**Details**

**Comment by thelostone-mc** [comment]
#### what all information we would store in the finalized distribution 

- merkle hash of distribution (stored in contract)
- distribution 
- other data used to calculate the distribution which may change over time (snapshot of the trust bonus score)


#### how would we store this on-chain (merkle hash + IPFS hash ?)

- merkle has would be on chain 
- all other data would be stored on IPFS and the hash would be stored in the conract

```
struct VotingResult {
  bytes32 resultsMerkleHash
  MetaPtr votingMetaPtr
}
```

#### In which contract would we store this 

Reason to keep it on the round contract

Having the final distribution added to the round contract makes sense 

- Just to keep the behaviour uniform (operator always interacts with the round and never the contract)
- You have one contract to fetch the distribution  & round info when you talk to the round contract 
**- the payout contract would be linked to the round and this means the round would be able to pass that information to payout contract**


Having the final distribution added to the voting contract makes sense  
- since vote contract deals with vote. it makes for the final distribution to be stored here (round doesn't need to know about votes)
- while you may to have invoke the round contract and then fetch the contract -> to fetch the distribution  (the subgraph can index this and make it available) 
- there is flexibility to allow every voting strategy to store it's own distribution format (argument can be made that is not useful cause all the data would be stored on IPFS)


I'm leaning to towards havin this on the round for the reason on being able to send info to the payout contract

**Comment by thelostone-mc** [comment]
Thanks @gravityblast for brainstorming with me on this <3
