### ISSUE TITLE
display program name instead of program id

### ISSUE THREAD

**Issue by shavinac** [gitcoinco/grants-round#440]
**User Story:**
As a round operator
I want to have a grant explorer landing page for my round
So that I have a place to send potential voters

**Acceptance Criteria**
GIVEN that I have created a round
WHEN I go to explorer.gitcoin.co/`chain_id`/`round_address`
THEN I see a page with **the name** of my program

**Product & Design Links:**\
- split out from #348 since it requires additional work
- plain text is fine — don't worry about formatting
- Updated design including Program Name here: https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=607%3A3131

**Tech Details:**
- note that this may require an additional lookup of program metadata (IPFS; program name is not directly indexed by subgraph

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by melissa-neira** [comment]
@shavinac I spoke with @lthrift yesterday and we realized that it made more sense to display the round name than the program name. For now, it doesn't make much sense to display the program name on GE because we're only dealing with individual rounds at the moment. I've updated the designs in Figma accordingly to show the round name instead. 

Sorry for the confusion!

**Comment by nfrgosselin** [comment]
@melissa-neira @shavinac I'm going to close this story as "not planned" given Melissa's note above
