### ISSUE TITLE
Page freeze during round creation

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#449]
**Overview**
Occasionally, the second page of the round creation flow won't allow the user to scroll. They end up having to refresh and start over. 

**Observed  behavior**
Page doesn't let the user scroll

**Expected behavior**
User should be able to scroll

**Screenshots**
[Loom video here](https://www.loom.com/share/3665c5a7996f4d52a539075b5bdca14c)

**Additional context**

Steps to reproduce:
1. Go to a program page and click "Create Round"
2. Enter in past dates in the first form page (but still following chronological rules of the application/round start/end dates). This will cause an error during submission because the contract will revert.
3. Click "next" to go to the next form page
4. Click "submit" and see that the "Deployment" step fails.
5. See the error modal. Click "Done"
6. Click "Previous" to return to the previous form page
7. Click "Next" to go to the next page
8. See that the page prohibits scrolling. Also see that the error modal pops up after ~2 seconds

Alternative steps to reproduce:
1. Go to a program page and click "Create Round"
2. Enter valid dates in the form. Click "next" to go to the next form page
3. Click "submit".
4. Reject the wallet transaction when it appears. This will cause an error during submission
5. Follow steps 5-8 as above

Dev notes:
* following the steps above - there is an added `overflow: hidden` style in the `<html>` tag when the scrolling is prevented. this style is not present during normal usage except when the modals are open. This seems to be a side effect of the error modal - `overflow: hidden` is set after clicking "Done" on the error modal

**Comment by shavinac** [comment]
Unable to reproduce the bug so far, but I have experienced it before 😖 

Until we have more information about the bug occurrences or (ideally) steps to reproduce, we can't investigate the bug any further

**Comment by shavinac** [comment]
Actually I discovered one way to reproduce a similar condition. See issue description

**Comment by shavinac** [comment]
Here's an issue in tailwind's headlessui repo with a very similar situation: https://github.com/tailwindlabs/headlessui/issues/1744#issuecomment-1208079384 

they have a dialog that is meant to open just as the first dialog closes, but due to transition animation times, the dialogs exist simultaneously, which is not supported by headlessui yet.

the two solutions proposed are:

1. nest the second dialog inside the first dialog. this means the first dialog is kept open while the second one is also open
2. delay the opening of the second dialog until the first dialog's transition animation is complete
