### ISSUE TITLE
Error deploying Grant Round on OP

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#493]
**Overview**
Optimism is testing round deployment and encountered a bug. I haven't been able to reproduce but screens are below

**Steps To Reproduce**
1. Deploy a program on Optimism
2. Within that program, create round and fill out information
3. Hit Launch
4. see error

**Observed  behavior**
Error screens (see screenshot)

**Expected behavior**
Round deploys and redirects you to round details page

**Screenshots**
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/15041635/194918034-72d9db4c-f448-4650-947e-fc49a50e58b7.png">
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/15041635/194918098-91f34dad-61b2-42c1-b900-0f2e834399ef.png">

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by bhargavaparoksham** [comment]
@nfrgosselin  Based on the error message in the console log screenshot shared, the above error is popping up because it seems the Optimism team is trying to create a round in the past. The _applicationsStartTime should be >= block.timestamp for this to not happen. 

Please refer to the code here, https://github.com/gitcoinco/grants-round/blob/30619a59708bb128ad649d34b09d1f33c7153ca0/packages/contracts/contracts/round/RoundImplementation.sol#L134


This issue can be fixed in the UI by doing date validation & showing the correct feedback as a popup if the round manager is entering the date in the past. I'll leave it upto you on deciding the priority of this.

cc: @thelostone-mc

**Comment by nfrgosselin** [comment]
Thanks for the write-up @bhargavaparoksham  — I have #450 in the backlog for this. I'll plan to pull it in next week
