### ISSUE TITLE
Project Cards: Adding project title + project owner + project description to project cards

### ISSUE THREAD

**Issue by melissa-neira** [gitcoinco/grants-round#692]
**User Story:**
As a user
I want to know a project's title, who it's by, and a short description of the project
So that I can have an informed browsing experience

**Acceptance Criteria**
- [ ] Project title (character limit 75 and then we show ellipses to indicate the title has been cut off)
- [ ] Project owner
- [ ] Short description: max 4 lines of text with ellipses at the end (indicating text cutoff)  

**Product & Design Links:**
[Figma](https://www.figma.com/file/lZwHrKYiWJna3AePzyTAiG/Grant-Explorer?node-id=1937%3A69606)

**Tech Details:**

**Open Questions:**

**Notes/Assumptions:**
- This includes writing test coverage for the functionality added in the ticket, if necessary

**Comment by bhargavaparoksham** [comment]
@nfrgosselin @melissa-neira What information should we display in case of "Project owner" here? 
We only have project owner addresses in the project metadata. There is no project owner name as such.

cc: @thelostone-mc

**Comment by melissa-neira** [comment]
@bhargavaparoksham let's show a shortened version of the project owner's address if possible. If we do show this, should it be clickable to something? If so, what can it show? I'm also fine with the address not being clickable. Thoughts @nfrgosselin?

**Comment by nfrgosselin** [comment]
@melissa-neira ya I like that shortened version of the address and the clickable idea.

@bhargavaparoksham how hard would it be to make it clickable to the block explorer for the chain the round is on? If it adds a lot of scope we can split this out into a different story and make it nice to have, and just go with a non-clickable shortened version for this story.

**Comment by bhargavaparoksham** [comment]
@nfrgosselin @melissa-neira  
1. Because each chain has its own explorer, it adda it bit of scope, it's better to make it a separate issue if we want the address to be clickable. 

2. Should the address be recipient address or the owner's address because there could be multiple owner addresses in most cases? Note that once user clicks on the project & goes to the project details page, we are showing the recipient address. So it makes sense to show the same on the Project card as well. Let me know?

**Comment by bhargavaparoksham** [comment]
@melissa-neira @nfrgosselin Perfect. The PR for this is ready now.
