### ISSUE TITLE
Error precision error when donating 

### ISSUE THREAD

**Issue by nfrgosselin** [gitcoinco/grants-round#801]
**Overview**
Reported by Gary

[grant-explorer.gitcoin.co-1670597034848.log](https://github.com/gitcoinco/grants-round/files/10196399/grant-explorer.gitcoin.co-1670597034848.log)

**Steps To Reproduce**

**Observed  behavior**
A clear and concise description of what the observed behavior of the system.

**Expected behavior**
A clear and concise description of what you expected the system to do.

**Screenshots**

**Additional context**
Add any other context about the problem here that will assist in triaging the bug. I.e. Browser information, unique identifiers, etc.

**Comment by hmrtn** [comment]
The log provided is here: 
https://discord.com/channels/562828676480237578/1035233199724445798/1050808480811978772

The issue has been identified. 

When a tx is submitted with 0.01 eth for all ten projects, there is a rounding error on the total sum - which leads to metamask and the UI being wonky. 

For example 0.01 eth to ten projects yields a total amount of 0.09999.... instead of 0.1 eth. 

<img width="1308" alt="Screenshot 2022-12-09 at 8 27 47 AM" src="https://user-images.githubusercontent.com/282867/206747477-4d33bd9b-19f5-47b8-bf1f-8250b9ed2f47.png">
