### ISSUE TITLE
graph: all applications status is now pending

### ISSUE THREAD

**Issue by zengatsu** [gitcoinco/grants-round#984]
![image](https://user-images.githubusercontent.com/760556/212416246-46cd1f83-8e5c-45bd-a8d8-beefc5fafbe6.png)

For the fantom round graph there this wasn't always the case, I am not sure when it changed but I think it was in the recent updates.
I have pulled data from the graph before it had the status, and also on the dashboard was showing applications with different status.

as for mainnet one where unicef round was hosted I think it was always showing pending for all projects since the beginning

**Comment by thelostone-mc** [comment]
@zengatsu that's because the IPFS integration from the graph is not reliable atm. 
It's been captured here : https://github.com/gitcoinco/grants-round/issues/410

The subgraph doesn't work well with IPFS calls and so to get around this , you'd have to fetch the projectsMetaPtr from the round contract. This is workaround until the graph fixes this (due for release end of Q1)

**Comment by thelostone-mc** [comment]
Closing this out as it's being tracked on #410
